services:
  - type: web
    name: signflow-backend
    runtime: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_cHJIeFSD1oV3@ep-empty-bush-a12s1uaj-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: SECRET_KEY
        generateValue: true
      - key: SIGNING_TOKEN_SECRET
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "480"
      - key: SIGNING_TOKEN_EXPIRE_HOURS
        value: "72"
      - key: EMAIL_PROVIDER
        value: "sendgrid"
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: SENDGRID_FROM_NAME
        value: "SignFlow"
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: ENVIRONMENT
        value: "production"
      - key: UPLOAD_FOLDER
        value: "./uploads"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false